"""
Django settings for gfconDjango project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wgmbs#vv-k&n^lomw^cguzf$k@a#nt*av7gp9d46@^*+h(t+#h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'gfcon.ddnsfree.com']

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	# Third-party apps
	"rest_framework",  # DRF 추가

	# Custom apps
	"api",  # API 앱 추가

	"corsheaders",
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	"corsheaders.middleware.CorsMiddleware",  # CORS 미들웨어 추가

]

ROOT_URLCONF = 'gfconDjango.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'gfconDjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# --------------------------- MONGODB ---------------------------

# 현재 프로젝트의 BASE_DIR
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# db_config를 모듈로 추가
sys.path.append(os.path.join(BASE_DIR, "db_config"))

# 환경 변수 로드
from dotenv import load_dotenv
load_dotenv()

# 환경 감지
DJANGO_ENV = os.getenv("DJANGO_ENV", "local")

MONGO_SERVER = None
MONGO_DB = None

if DJANGO_ENV == "production":
    from db_config.production import init_mongodb  # 절대 경로 사용
    MONGODB_DB = init_mongodb()
else:
    from db_config.local import connect_mongodb_via_ssh  # 절대 경로 사용
    MONGODB_SERVER, MONGODB_DB = connect_mongodb_via_ssh()

# --------------------------- POSTGRESQL ---------------------------
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': os.getenv("POSTGRES_DB"),
		'USER': os.getenv("POSTGRES_USER"),
		'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
		'HOST': os.getenv("POSTGRES_HOST"),
		'PORT': os.getenv("POSTGRES_PORT"),
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS 설정 (React와 통신 허용)
CORS_ALLOWED_ORIGINS = [
	"http://localhost:5173",
	"http://172.30.1.81:5173",
	"http://gfcon.ddnsfree.com:5173",
	"http://gfcon.ddnsfree.com",
]

CSRF_TRUSTED_ORIGINS = [
	"http://localhost:5173",
	"http://172.30.1.81:5173",
	"http://gfcon.ddnsfree.com:5173",
]

CSRF_COOKIE_SECURE = False  # 개발 환경에서는 False로 설정
